// <auto-generated />
using System;
using CountryWeatherAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CountryWeatherAPI.Migrations
{
    [DbContext(typeof(CountryWeatherDbContext))]
    partial class CountryWeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountryWeatherAPI.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LatitudeRangeEnd")
                        .HasColumnType("integer");

                    b.Property<int>("LatitudeRangeStart")
                        .HasColumnType("integer");

                    b.Property<int>("LongitudeRangeEnd")
                        .HasColumnType("integer");

                    b.Property<int>("LongitudeRangeStart")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResponsiblePersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsiblePersonId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LatitudeRangeEnd = 39,
                            LatitudeRangeStart = 30,
                            LongitudeRangeEnd = 75,
                            LongitudeRangeStart = 60,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            LatitudeRangeEnd = 43,
                            LatitudeRangeStart = 39,
                            LongitudeRangeEnd = 21,
                            LongitudeRangeStart = 19,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            LatitudeRangeEnd = 37,
                            LatitudeRangeStart = 19,
                            LongitudeRangeEnd = 12,
                            LongitudeRangeStart = -9,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            LatitudeRangeEnd = 43,
                            LatitudeRangeStart = 42,
                            LongitudeRangeEnd = 2,
                            LongitudeRangeStart = 1,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            LatitudeRangeEnd = -4,
                            LatitudeRangeStart = -18,
                            LongitudeRangeEnd = 24,
                            LongitudeRangeStart = 12,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            LatitudeRangeEnd = 18,
                            LatitudeRangeStart = 16,
                            LongitudeRangeEnd = -61,
                            LongitudeRangeStart = -62,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            LatitudeRangeEnd = -22,
                            LatitudeRangeStart = -55,
                            LongitudeRangeEnd = -53,
                            LongitudeRangeStart = -73,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            LatitudeRangeEnd = 42,
                            LatitudeRangeStart = 39,
                            LongitudeRangeEnd = 47,
                            LongitudeRangeStart = 44,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            LatitudeRangeEnd = -10,
                            LatitudeRangeStart = -43,
                            LongitudeRangeEnd = 154,
                            LongitudeRangeStart = 113,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            LatitudeRangeEnd = 49,
                            LatitudeRangeStart = 46,
                            LongitudeRangeEnd = 17,
                            LongitudeRangeStart = 9,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            LatitudeRangeEnd = 42,
                            LatitudeRangeStart = 38,
                            LongitudeRangeEnd = 51,
                            LongitudeRangeStart = 44,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            LatitudeRangeEnd = 27,
                            LatitudeRangeStart = 20,
                            LongitudeRangeEnd = -72,
                            LongitudeRangeStart = -79,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            LatitudeRangeEnd = 26,
                            LatitudeRangeStart = 25,
                            LongitudeRangeEnd = 51,
                            LongitudeRangeStart = 50,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            LatitudeRangeEnd = 27,
                            LatitudeRangeStart = 20,
                            LongitudeRangeEnd = 93,
                            LongitudeRangeStart = 88,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            LatitudeRangeEnd = 14,
                            LatitudeRangeStart = 13,
                            LongitudeRangeEnd = -59,
                            LongitudeRangeStart = -59,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            LatitudeRangeEnd = 57,
                            LatitudeRangeStart = 52,
                            LongitudeRangeEnd = 33,
                            LongitudeRangeStart = 24,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            LatitudeRangeEnd = 51,
                            LatitudeRangeStart = 50,
                            LongitudeRangeEnd = 6,
                            LongitudeRangeStart = 2,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            LatitudeRangeEnd = 18,
                            LatitudeRangeStart = 16,
                            LongitudeRangeEnd = -88,
                            LongitudeRangeStart = -89,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            LatitudeRangeEnd = 12,
                            LatitudeRangeStart = 6,
                            LongitudeRangeEnd = 4,
                            LongitudeRangeStart = 0,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            LatitudeRangeEnd = 29,
                            LatitudeRangeStart = 27,
                            LongitudeRangeEnd = 92,
                            LongitudeRangeStart = 88,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            LatitudeRangeEnd = -9,
                            LatitudeRangeStart = -23,
                            LongitudeRangeEnd = -57,
                            LongitudeRangeStart = -69,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            LatitudeRangeEnd = 45,
                            LatitudeRangeStart = 42,
                            LongitudeRangeEnd = 20,
                            LongitudeRangeStart = 15,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            LatitudeRangeEnd = -18,
                            LatitudeRangeStart = -27,
                            LongitudeRangeEnd = 30,
                            LongitudeRangeStart = 20,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            LatitudeRangeEnd = 5,
                            LatitudeRangeStart = -34,
                            LongitudeRangeEnd = -34,
                            LongitudeRangeStart = -74,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            LatitudeRangeEnd = 5,
                            LatitudeRangeStart = 4,
                            LongitudeRangeEnd = 115,
                            LongitudeRangeStart = 114,
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 26,
                            LatitudeRangeEnd = 44,
                            LatitudeRangeStart = 41,
                            LongitudeRangeEnd = 29,
                            LongitudeRangeStart = 22,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            LatitudeRangeEnd = 15,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = 3,
                            LongitudeRangeStart = -6,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            LatitudeRangeEnd = -2,
                            LatitudeRangeStart = -4,
                            LongitudeRangeEnd = 30,
                            LongitudeRangeStart = 29,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            LatitudeRangeEnd = 18,
                            LatitudeRangeStart = 16,
                            LongitudeRangeEnd = -22,
                            LongitudeRangeStart = -26,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            LatitudeRangeEnd = 15,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = 108,
                            LongitudeRangeStart = 102,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            LatitudeRangeEnd = 13,
                            LatitudeRangeStart = 2,
                            LongitudeRangeEnd = 17,
                            LongitudeRangeStart = 8,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            LatitudeRangeEnd = 84,
                            LatitudeRangeStart = 42,
                            LongitudeRangeEnd = -52,
                            LongitudeRangeStart = -141,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            LatitudeRangeEnd = 11,
                            LatitudeRangeStart = 2,
                            LongitudeRangeEnd = 28,
                            LongitudeRangeStart = 14,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            LatitudeRangeEnd = 24,
                            LatitudeRangeStart = 7,
                            LongitudeRangeEnd = 24,
                            LongitudeRangeStart = 13,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            LatitudeRangeEnd = -18,
                            LatitudeRangeStart = -56,
                            LongitudeRangeEnd = -66,
                            LongitudeRangeStart = -75,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            LatitudeRangeEnd = 53,
                            LatitudeRangeStart = 18,
                            LongitudeRangeEnd = 135,
                            LongitudeRangeStart = 73,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            LatitudeRangeEnd = 13,
                            LatitudeRangeStart = -4,
                            LongitudeRangeEnd = -66,
                            LongitudeRangeStart = -79,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            LatitudeRangeEnd = -11,
                            LatitudeRangeStart = -12,
                            LongitudeRangeEnd = 44,
                            LongitudeRangeStart = 43,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            LatitudeRangeEnd = 5,
                            LatitudeRangeStart = -5,
                            LongitudeRangeEnd = 31,
                            LongitudeRangeStart = 12,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40,
                            LatitudeRangeEnd = 11,
                            LatitudeRangeStart = 8,
                            LongitudeRangeEnd = -82,
                            LongitudeRangeStart = -86,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 41,
                            LatitudeRangeEnd = 47,
                            LatitudeRangeStart = 42,
                            LongitudeRangeEnd = 20,
                            LongitudeRangeStart = 14,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            LatitudeRangeEnd = 23,
                            LatitudeRangeStart = 20,
                            LongitudeRangeEnd = -74,
                            LongitudeRangeStart = -85,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 43,
                            LatitudeRangeEnd = 36,
                            LatitudeRangeStart = 35,
                            LongitudeRangeEnd = 34,
                            LongitudeRangeStart = 32,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 44,
                            LatitudeRangeEnd = 51,
                            LatitudeRangeStart = 48,
                            LongitudeRangeEnd = 19,
                            LongitudeRangeStart = 12,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 45,
                            LatitudeRangeEnd = 58,
                            LatitudeRangeStart = 54,
                            LongitudeRangeEnd = 15,
                            LongitudeRangeStart = 8,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 46,
                            LatitudeRangeEnd = 12,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = 44,
                            LongitudeRangeStart = 41,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 47,
                            LatitudeRangeEnd = 16,
                            LatitudeRangeStart = 15,
                            LongitudeRangeEnd = -61,
                            LongitudeRangeStart = -62,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 48,
                            LatitudeRangeEnd = 20,
                            LatitudeRangeStart = 17,
                            LongitudeRangeEnd = -68,
                            LongitudeRangeStart = -72,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 49,
                            LatitudeRangeEnd = 2,
                            LatitudeRangeStart = -5,
                            LongitudeRangeEnd = -75,
                            LongitudeRangeStart = -81,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 50,
                            LatitudeRangeEnd = 32,
                            LatitudeRangeStart = 22,
                            LongitudeRangeEnd = 35,
                            LongitudeRangeStart = 25,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 51,
                            LatitudeRangeEnd = 15,
                            LatitudeRangeStart = 13,
                            LongitudeRangeEnd = -88,
                            LongitudeRangeStart = -91,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 52,
                            LatitudeRangeEnd = 3,
                            LatitudeRangeStart = 0,
                            LongitudeRangeEnd = 12,
                            LongitudeRangeStart = 8,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 53,
                            LatitudeRangeEnd = 18,
                            LatitudeRangeStart = 12,
                            LongitudeRangeEnd = 43,
                            LongitudeRangeStart = 36,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 54,
                            LatitudeRangeEnd = 60,
                            LatitudeRangeStart = 57,
                            LongitudeRangeEnd = 29,
                            LongitudeRangeStart = 21,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 55,
                            LatitudeRangeEnd = -25,
                            LatitudeRangeStart = -27,
                            LongitudeRangeEnd = 32,
                            LongitudeRangeStart = 31,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 56,
                            LatitudeRangeEnd = 15,
                            LatitudeRangeStart = 3,
                            LongitudeRangeEnd = 48,
                            LongitudeRangeStart = 33,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 57,
                            LatitudeRangeEnd = -12,
                            LatitudeRangeStart = -21,
                            LongitudeRangeEnd = 178,
                            LongitudeRangeStart = 177,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 58,
                            LatitudeRangeEnd = 70,
                            LatitudeRangeStart = 60,
                            LongitudeRangeEnd = 32,
                            LongitudeRangeStart = 20,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 59,
                            LatitudeRangeEnd = 51,
                            LatitudeRangeStart = 41,
                            LongitudeRangeEnd = 10,
                            LongitudeRangeStart = -5,
                            Name = "France"
                        },
                        new
                        {
                            Id = 60,
                            LatitudeRangeEnd = 3,
                            LatitudeRangeStart = -4,
                            LongitudeRangeEnd = 15,
                            LongitudeRangeStart = 8,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 61,
                            LatitudeRangeEnd = 14,
                            LatitudeRangeStart = 13,
                            LongitudeRangeEnd = -15,
                            LongitudeRangeStart = -17,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 62,
                            LatitudeRangeEnd = 44,
                            LatitudeRangeStart = 42,
                            LongitudeRangeEnd = 47,
                            LongitudeRangeStart = 40,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 63,
                            LatitudeRangeEnd = 55,
                            LatitudeRangeStart = 47,
                            LongitudeRangeEnd = 15,
                            LongitudeRangeStart = 5,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 64,
                            LatitudeRangeEnd = 12,
                            LatitudeRangeStart = 4,
                            LongitudeRangeEnd = 1,
                            LongitudeRangeStart = -3,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 65,
                            LatitudeRangeEnd = 42,
                            LatitudeRangeStart = 35,
                            LongitudeRangeEnd = 29,
                            LongitudeRangeStart = 19,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 66,
                            LatitudeRangeEnd = 13,
                            LatitudeRangeStart = 11,
                            LongitudeRangeEnd = -61,
                            LongitudeRangeStart = -62,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 67,
                            LatitudeRangeEnd = 18,
                            LatitudeRangeStart = 14,
                            LongitudeRangeEnd = -88,
                            LongitudeRangeStart = -93,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 68,
                            LatitudeRangeEnd = 12,
                            LatitudeRangeStart = 7,
                            LongitudeRangeEnd = -7,
                            LongitudeRangeStart = -15,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 69,
                            LatitudeRangeEnd = 12,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = -13,
                            LongitudeRangeStart = -17,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 70,
                            LatitudeRangeEnd = 9,
                            LatitudeRangeStart = 1,
                            LongitudeRangeEnd = -57,
                            LongitudeRangeStart = -61,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 71,
                            LatitudeRangeEnd = 20,
                            LatitudeRangeStart = 18,
                            LongitudeRangeEnd = -71,
                            LongitudeRangeStart = -75,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 72,
                            LatitudeRangeEnd = 17,
                            LatitudeRangeStart = 13,
                            LongitudeRangeEnd = -83,
                            LongitudeRangeStart = -89,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 73,
                            LatitudeRangeEnd = 48,
                            LatitudeRangeStart = 46,
                            LongitudeRangeEnd = 23,
                            LongitudeRangeStart = 16,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 74,
                            LatitudeRangeEnd = 67,
                            LatitudeRangeStart = 63,
                            LongitudeRangeEnd = -13,
                            LongitudeRangeStart = -24,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 75,
                            LatitudeRangeEnd = 36,
                            LatitudeRangeStart = 8,
                            LongitudeRangeEnd = 98,
                            LongitudeRangeStart = 68,
                            Name = "India"
                        },
                        new
                        {
                            Id = 76,
                            LatitudeRangeEnd = 6,
                            LatitudeRangeStart = -11,
                            LongitudeRangeEnd = 141,
                            LongitudeRangeStart = 95,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 77,
                            LatitudeRangeEnd = 40,
                            LatitudeRangeStart = 25,
                            LongitudeRangeEnd = 63,
                            LongitudeRangeStart = 44,
                            Name = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = 78,
                            LatitudeRangeEnd = 38,
                            LatitudeRangeStart = 29,
                            LongitudeRangeEnd = 49,
                            LongitudeRangeStart = 39,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 79,
                            LatitudeRangeEnd = 55,
                            LatitudeRangeStart = 51,
                            LongitudeRangeEnd = -5,
                            LongitudeRangeStart = -11,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 80,
                            LatitudeRangeEnd = 34,
                            LatitudeRangeStart = 29,
                            LongitudeRangeEnd = 36,
                            LongitudeRangeStart = 34,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 81,
                            LatitudeRangeEnd = 47,
                            LatitudeRangeStart = 36,
                            LongitudeRangeEnd = 19,
                            LongitudeRangeStart = 6,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 82,
                            LatitudeRangeEnd = 19,
                            LatitudeRangeStart = 17,
                            LongitudeRangeEnd = -76,
                            LongitudeRangeStart = -79,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 83,
                            LatitudeRangeEnd = 46,
                            LatitudeRangeStart = 24,
                            LongitudeRangeEnd = 153,
                            LongitudeRangeStart = 123,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 84,
                            LatitudeRangeEnd = 34,
                            LatitudeRangeStart = 29,
                            LongitudeRangeEnd = 39,
                            LongitudeRangeStart = 35,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 85,
                            LatitudeRangeEnd = 56,
                            LatitudeRangeStart = 40,
                            LongitudeRangeEnd = 88,
                            LongitudeRangeStart = 46,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 86,
                            LatitudeRangeEnd = 5,
                            LatitudeRangeStart = -4,
                            LongitudeRangeEnd = 42,
                            LongitudeRangeStart = 34,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 87,
                            LatitudeRangeEnd = 4,
                            LatitudeRangeStart = -4,
                            LongitudeRangeEnd = 173,
                            LongitudeRangeStart = 169,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 88,
                            LatitudeRangeEnd = 30,
                            LatitudeRangeStart = 28,
                            LongitudeRangeEnd = 49,
                            LongitudeRangeStart = 46,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 89,
                            LatitudeRangeEnd = 43,
                            LatitudeRangeStart = 39,
                            LongitudeRangeEnd = 81,
                            LongitudeRangeStart = 69,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 90,
                            LatitudeRangeEnd = 23,
                            LatitudeRangeStart = 14,
                            LongitudeRangeEnd = 108,
                            LongitudeRangeStart = 100,
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 91,
                            LatitudeRangeEnd = 58,
                            LatitudeRangeStart = 56,
                            LongitudeRangeEnd = 29,
                            LongitudeRangeStart = 21,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 92,
                            LatitudeRangeEnd = 34,
                            LatitudeRangeStart = 33,
                            LongitudeRangeEnd = 37,
                            LongitudeRangeStart = 35,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 93,
                            LatitudeRangeEnd = -28,
                            LatitudeRangeStart = -30,
                            LongitudeRangeEnd = 29,
                            LongitudeRangeStart = 27,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 94,
                            LatitudeRangeEnd = 9,
                            LatitudeRangeStart = 4,
                            LongitudeRangeEnd = -7,
                            LongitudeRangeStart = -12,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 95,
                            LatitudeRangeEnd = 34,
                            LatitudeRangeStart = 19,
                            LongitudeRangeEnd = 26,
                            LongitudeRangeStart = 10,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 96,
                            LatitudeRangeEnd = 48,
                            LatitudeRangeStart = 47,
                            LongitudeRangeEnd = 10,
                            LongitudeRangeStart = 9,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 97,
                            LatitudeRangeEnd = 57,
                            LatitudeRangeStart = 54,
                            LongitudeRangeEnd = 27,
                            LongitudeRangeStart = 20,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 98,
                            LatitudeRangeEnd = 51,
                            LatitudeRangeStart = 49,
                            LongitudeRangeEnd = 7,
                            LongitudeRangeStart = 5,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 99,
                            LatitudeRangeEnd = -12,
                            LatitudeRangeStart = -26,
                            LongitudeRangeEnd = 51,
                            LongitudeRangeStart = 43,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 100,
                            LatitudeRangeEnd = -9,
                            LatitudeRangeStart = -17,
                            LongitudeRangeEnd = 36,
                            LongitudeRangeStart = 32,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 101,
                            LatitudeRangeEnd = 7,
                            LatitudeRangeStart = 1,
                            LongitudeRangeEnd = 119,
                            LongitudeRangeStart = 100,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 102,
                            LatitudeRangeEnd = 7,
                            LatitudeRangeStart = -1,
                            LongitudeRangeEnd = 74,
                            LongitudeRangeStart = 72,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 103,
                            LatitudeRangeEnd = 25,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = 5,
                            LongitudeRangeStart = -12,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 104,
                            LatitudeRangeEnd = 36,
                            LatitudeRangeStart = 35,
                            LongitudeRangeEnd = 15,
                            LongitudeRangeStart = 14,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 105,
                            LatitudeRangeEnd = 15,
                            LatitudeRangeStart = 5,
                            LongitudeRangeEnd = 173,
                            LongitudeRangeStart = 162,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 106,
                            LatitudeRangeEnd = 27,
                            LatitudeRangeStart = 15,
                            LongitudeRangeEnd = -4,
                            LongitudeRangeStart = -17,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 107,
                            LatitudeRangeEnd = -19,
                            LatitudeRangeStart = -21,
                            LongitudeRangeEnd = 58,
                            LongitudeRangeStart = 56,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 108,
                            LatitudeRangeEnd = 33,
                            LatitudeRangeStart = 15,
                            LongitudeRangeEnd = -86,
                            LongitudeRangeStart = -118,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 109,
                            LatitudeRangeEnd = 10,
                            LatitudeRangeStart = 0,
                            LongitudeRangeEnd = 162,
                            LongitudeRangeStart = 138,
                            Name = "Micronesia (Federated States of)"
                        },
                        new
                        {
                            Id = 110,
                            LatitudeRangeEnd = 44,
                            LatitudeRangeStart = 43,
                            LongitudeRangeEnd = 8,
                            LongitudeRangeStart = 7,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 111,
                            LatitudeRangeEnd = 52,
                            LatitudeRangeStart = 41,
                            LongitudeRangeEnd = 120,
                            LongitudeRangeStart = 87,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 112,
                            LatitudeRangeEnd = 43,
                            LatitudeRangeStart = 41,
                            LongitudeRangeEnd = 21,
                            LongitudeRangeStart = 18,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 113,
                            LatitudeRangeEnd = 36,
                            LatitudeRangeStart = 27,
                            LongitudeRangeEnd = -2,
                            LongitudeRangeStart = -13,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 114,
                            LatitudeRangeEnd = -10,
                            LatitudeRangeStart = -27,
                            LongitudeRangeEnd = 41,
                            LongitudeRangeStart = 30,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 115,
                            LatitudeRangeEnd = 29,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = 102,
                            LongitudeRangeStart = 92,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 116,
                            LatitudeRangeEnd = -17,
                            LatitudeRangeStart = -29,
                            LongitudeRangeEnd = 25,
                            LongitudeRangeStart = 12,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 117,
                            LatitudeRangeEnd = -1,
                            LatitudeRangeStart = -1,
                            LongitudeRangeEnd = 167,
                            LongitudeRangeStart = 166,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 118,
                            LatitudeRangeEnd = 31,
                            LatitudeRangeStart = 27,
                            LongitudeRangeEnd = 89,
                            LongitudeRangeStart = 80,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 119,
                            LatitudeRangeEnd = 54,
                            LatitudeRangeStart = 50,
                            LongitudeRangeEnd = 8,
                            LongitudeRangeStart = 3,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 120,
                            LatitudeRangeEnd = -34,
                            LatitudeRangeStart = -47,
                            LongitudeRangeEnd = 179,
                            LongitudeRangeStart = 166,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 121,
                            LatitudeRangeEnd = 15,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = -82,
                            LongitudeRangeStart = -88,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 122,
                            LatitudeRangeEnd = 24,
                            LatitudeRangeStart = 11,
                            LongitudeRangeEnd = 16,
                            LongitudeRangeStart = 0,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 123,
                            LatitudeRangeEnd = 14,
                            LatitudeRangeStart = 4,
                            LongitudeRangeEnd = 15,
                            LongitudeRangeStart = 3,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 124,
                            LatitudeRangeEnd = 42,
                            LatitudeRangeStart = 40,
                            LongitudeRangeEnd = 23,
                            LongitudeRangeStart = 20,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 125,
                            LatitudeRangeEnd = 71,
                            LatitudeRangeStart = 58,
                            LongitudeRangeEnd = 32,
                            LongitudeRangeStart = 4,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 126,
                            LatitudeRangeEnd = 26,
                            LatitudeRangeStart = 17,
                            LongitudeRangeEnd = 60,
                            LongitudeRangeStart = 52,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 127,
                            LatitudeRangeEnd = 37,
                            LatitudeRangeStart = 24,
                            LongitudeRangeEnd = 77,
                            LongitudeRangeStart = 60,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 128,
                            LatitudeRangeEnd = 8,
                            LatitudeRangeStart = 6,
                            LongitudeRangeEnd = 135,
                            LongitudeRangeStart = 131,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 129,
                            LatitudeRangeEnd = 10,
                            LatitudeRangeStart = 8,
                            LongitudeRangeEnd = -77,
                            LongitudeRangeStart = -83,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 130,
                            LatitudeRangeEnd = -1,
                            LatitudeRangeStart = -12,
                            LongitudeRangeEnd = 160,
                            LongitudeRangeStart = 140,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 131,
                            LatitudeRangeEnd = -19,
                            LatitudeRangeStart = -27,
                            LongitudeRangeEnd = -54,
                            LongitudeRangeStart = -62,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 132,
                            LatitudeRangeEnd = 0,
                            LatitudeRangeStart = -18,
                            LongitudeRangeEnd = -68,
                            LongitudeRangeStart = -81,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 133,
                            LatitudeRangeEnd = 21,
                            LatitudeRangeStart = 4,
                            LongitudeRangeEnd = 127,
                            LongitudeRangeStart = 115,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 134,
                            LatitudeRangeEnd = 55,
                            LatitudeRangeStart = 49,
                            LongitudeRangeEnd = 25,
                            LongitudeRangeStart = 14,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 135,
                            LatitudeRangeEnd = 43,
                            LatitudeRangeStart = 37,
                            LongitudeRangeEnd = -6,
                            LongitudeRangeStart = -9,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 136,
                            LatitudeRangeEnd = 27,
                            LatitudeRangeStart = 24,
                            LongitudeRangeEnd = 52,
                            LongitudeRangeStart = 50,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 137,
                            LatitudeRangeEnd = 39,
                            LatitudeRangeStart = 33,
                            LongitudeRangeEnd = 130,
                            LongitudeRangeStart = 125,
                            Name = "Republic of Korea"
                        },
                        new
                        {
                            Id = 138,
                            LatitudeRangeEnd = 48,
                            LatitudeRangeStart = 45,
                            LongitudeRangeEnd = 30,
                            LongitudeRangeStart = 27,
                            Name = "Republic of Moldova"
                        },
                        new
                        {
                            Id = 139,
                            LatitudeRangeEnd = 48,
                            LatitudeRangeStart = 44,
                            LongitudeRangeEnd = 30,
                            LongitudeRangeStart = 20,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 140,
                            LatitudeRangeEnd = 82,
                            LatitudeRangeStart = 41,
                            LongitudeRangeEnd = 190,
                            LongitudeRangeStart = 19,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 141,
                            LatitudeRangeEnd = -1,
                            LatitudeRangeStart = -3,
                            LongitudeRangeEnd = 31,
                            LongitudeRangeStart = 29,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 142,
                            LatitudeRangeEnd = 18,
                            LatitudeRangeStart = 17,
                            LongitudeRangeEnd = -62,
                            LongitudeRangeStart = -63,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 143,
                            LatitudeRangeEnd = 14,
                            LatitudeRangeStart = 13,
                            LongitudeRangeEnd = -60,
                            LongitudeRangeStart = -62,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 144,
                            LatitudeRangeEnd = 14,
                            LatitudeRangeStart = 12,
                            LongitudeRangeEnd = -60,
                            LongitudeRangeStart = -62,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 145,
                            LatitudeRangeEnd = -13,
                            LatitudeRangeStart = -14,
                            LongitudeRangeEnd = -171,
                            LongitudeRangeStart = -173,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 146,
                            LatitudeRangeEnd = 44,
                            LatitudeRangeStart = 43,
                            LongitudeRangeEnd = 13,
                            LongitudeRangeStart = 12,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 147,
                            LatitudeRangeEnd = 2,
                            LatitudeRangeStart = 0,
                            LongitudeRangeEnd = 7,
                            LongitudeRangeStart = 6,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 148,
                            LatitudeRangeEnd = 32,
                            LatitudeRangeStart = 16,
                            LongitudeRangeEnd = 56,
                            LongitudeRangeStart = 34,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 149,
                            LatitudeRangeEnd = 17,
                            LatitudeRangeStart = 12,
                            LongitudeRangeEnd = -11,
                            LongitudeRangeStart = -17,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 150,
                            LatitudeRangeEnd = 44,
                            LatitudeRangeStart = 42,
                            LongitudeRangeEnd = 22,
                            LongitudeRangeStart = 19,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 151,
                            LatitudeRangeEnd = -4,
                            LatitudeRangeStart = -5,
                            LongitudeRangeEnd = 57,
                            LongitudeRangeStart = 55,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 152,
                            LatitudeRangeEnd = 10,
                            LatitudeRangeStart = 6,
                            LongitudeRangeEnd = -10,
                            LongitudeRangeStart = -13,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 153,
                            LatitudeRangeEnd = 2,
                            LatitudeRangeStart = 1,
                            LongitudeRangeEnd = 105,
                            LongitudeRangeStart = 103,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 154,
                            LatitudeRangeEnd = 50,
                            LatitudeRangeStart = 48,
                            LongitudeRangeEnd = 23,
                            LongitudeRangeStart = 16,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 155,
                            LatitudeRangeEnd = 47,
                            LatitudeRangeStart = 46,
                            LongitudeRangeEnd = 17,
                            LongitudeRangeStart = 13,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 156,
                            LatitudeRangeEnd = -6,
                            LatitudeRangeStart = -12,
                            LongitudeRangeEnd = 168,
                            LongitudeRangeStart = 155,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 157,
                            LatitudeRangeEnd = 12,
                            LatitudeRangeStart = -1,
                            LongitudeRangeEnd = 52,
                            LongitudeRangeStart = 41,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 158,
                            LatitudeRangeEnd = -22,
                            LatitudeRangeStart = -35,
                            LongitudeRangeEnd = 33,
                            LongitudeRangeStart = 16,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 159,
                            LatitudeRangeEnd = 12,
                            LatitudeRangeStart = 3,
                            LongitudeRangeEnd = 36,
                            LongitudeRangeStart = 24,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 160,
                            LatitudeRangeEnd = 43,
                            LatitudeRangeStart = 28,
                            LongitudeRangeEnd = 4,
                            LongitudeRangeStart = -18,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 161,
                            LatitudeRangeEnd = 10,
                            LatitudeRangeStart = 6,
                            LongitudeRangeEnd = 82,
                            LongitudeRangeStart = 79,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 162,
                            LatitudeRangeEnd = 33,
                            LatitudeRangeStart = 31,
                            LongitudeRangeEnd = 35,
                            LongitudeRangeStart = 34,
                            Name = "State of Palestine"
                        },
                        new
                        {
                            Id = 163,
                            LatitudeRangeEnd = 22,
                            LatitudeRangeStart = 9,
                            LongitudeRangeEnd = 39,
                            LongitudeRangeStart = 22,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 164,
                            LatitudeRangeEnd = 6,
                            LatitudeRangeStart = 2,
                            LongitudeRangeEnd = -54,
                            LongitudeRangeStart = -59,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 165,
                            LatitudeRangeEnd = 70,
                            LatitudeRangeStart = 56,
                            LongitudeRangeEnd = 25,
                            LongitudeRangeStart = 11,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 166,
                            LatitudeRangeEnd = 48,
                            LatitudeRangeStart = 46,
                            LongitudeRangeEnd = 10,
                            LongitudeRangeStart = 6,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 167,
                            LatitudeRangeEnd = 37,
                            LatitudeRangeStart = 32,
                            LongitudeRangeEnd = 42,
                            LongitudeRangeStart = 35,
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 168,
                            LatitudeRangeEnd = 41,
                            LatitudeRangeStart = 36,
                            LongitudeRangeEnd = 75,
                            LongitudeRangeStart = 67,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 169,
                            LatitudeRangeEnd = 21,
                            LatitudeRangeStart = 5,
                            LongitudeRangeEnd = 105,
                            LongitudeRangeStart = 97,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 170,
                            LatitudeRangeEnd = -8,
                            LatitudeRangeStart = -9,
                            LongitudeRangeEnd = 128,
                            LongitudeRangeStart = 125,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 171,
                            LatitudeRangeEnd = 11,
                            LatitudeRangeStart = 6,
                            LongitudeRangeEnd = 2,
                            LongitudeRangeStart = -1,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 172,
                            LatitudeRangeEnd = -16,
                            LatitudeRangeStart = -22,
                            LongitudeRangeEnd = -173,
                            LongitudeRangeStart = -177,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 173,
                            LatitudeRangeEnd = 11,
                            LatitudeRangeStart = 10,
                            LongitudeRangeEnd = -60,
                            LongitudeRangeStart = -62,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 174,
                            LatitudeRangeEnd = 38,
                            LatitudeRangeStart = 30,
                            LongitudeRangeEnd = 12,
                            LongitudeRangeStart = 7,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 175,
                            LatitudeRangeEnd = 42,
                            LatitudeRangeStart = 36,
                            LongitudeRangeEnd = 45,
                            LongitudeRangeStart = 26,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 176,
                            LatitudeRangeEnd = 43,
                            LatitudeRangeStart = 35,
                            LongitudeRangeEnd = 66,
                            LongitudeRangeStart = 52,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 177,
                            LatitudeRangeEnd = -6,
                            LatitudeRangeStart = -9,
                            LongitudeRangeEnd = 180,
                            LongitudeRangeStart = 176,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 178,
                            LatitudeRangeEnd = 4,
                            LatitudeRangeStart = -2,
                            LongitudeRangeEnd = 36,
                            LongitudeRangeStart = 30,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 179,
                            LatitudeRangeEnd = 53,
                            LatitudeRangeStart = 45,
                            LongitudeRangeEnd = 41,
                            LongitudeRangeStart = 23,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 180,
                            LatitudeRangeEnd = 26,
                            LatitudeRangeStart = 23,
                            LongitudeRangeEnd = 57,
                            LongitudeRangeStart = 51,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 181,
                            LatitudeRangeEnd = 60,
                            LatitudeRangeStart = 50,
                            LongitudeRangeEnd = 2,
                            LongitudeRangeStart = -8,
                            Name = "United Kingdom of Great Britain and Northern Ireland"
                        },
                        new
                        {
                            Id = 182,
                            LatitudeRangeEnd = 0,
                            LatitudeRangeStart = -12,
                            LongitudeRangeEnd = 41,
                            LongitudeRangeStart = 30,
                            Name = "United Republic of Tanzania"
                        },
                        new
                        {
                            Id = 183,
                            LatitudeRangeEnd = 49,
                            LatitudeRangeStart = 25,
                            LongitudeRangeEnd = -67,
                            LongitudeRangeStart = -125,
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 184,
                            LatitudeRangeEnd = -30,
                            LatitudeRangeStart = -35,
                            LongitudeRangeEnd = -53,
                            LongitudeRangeStart = -58,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 185,
                            LatitudeRangeEnd = 46,
                            LatitudeRangeStart = 37,
                            LongitudeRangeEnd = 73,
                            LongitudeRangeStart = 56,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 186,
                            LatitudeRangeEnd = -12,
                            LatitudeRangeStart = -17,
                            LongitudeRangeEnd = 171,
                            LongitudeRangeStart = 166,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 187,
                            LatitudeRangeEnd = 13,
                            LatitudeRangeStart = 1,
                            LongitudeRangeEnd = -59,
                            LongitudeRangeStart = -73,
                            Name = "Venezuela (Bolivarian Republic of)"
                        },
                        new
                        {
                            Id = 188,
                            LatitudeRangeEnd = 24,
                            LatitudeRangeStart = 9,
                            LongitudeRangeEnd = 110,
                            LongitudeRangeStart = 102,
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 189,
                            LatitudeRangeEnd = 19,
                            LatitudeRangeStart = 12,
                            LongitudeRangeEnd = 54,
                            LongitudeRangeStart = 42,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 190,
                            LatitudeRangeEnd = -8,
                            LatitudeRangeStart = -18,
                            LongitudeRangeEnd = 34,
                            LongitudeRangeStart = 22,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 191,
                            LatitudeRangeEnd = -15,
                            LatitudeRangeStart = -22,
                            LongitudeRangeEnd = 34,
                            LongitudeRangeStart = 26,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("CountryWeatherAPI.Models.ResponsiblePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName", "BirthDate")
                        .IsUnique();

                    b.ToTable("ResponsiblePersons");
                });

            modelBuilder.Entity("CountryWeatherAPI.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<double>("FeelsLike")
                        .HasColumnType("double precision");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<int>("Latitude")
                        .HasColumnType("integer");

                    b.Property<int>("Longitude")
                        .HasColumnType("integer");

                    b.Property<double>("Pressure")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeatherMain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WindDeg")
                        .HasColumnType("integer");

                    b.Property<double>("WindGust")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("CountryWeatherAPI.Models.Country", b =>
                {
                    b.HasOne("CountryWeatherAPI.Models.ResponsiblePerson", "ResponsiblePerson")
                        .WithMany("Countries")
                        .HasForeignKey("ResponsiblePersonId");

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("CountryWeatherAPI.Models.Weather", b =>
                {
                    b.HasOne("CountryWeatherAPI.Models.Country", "Country")
                        .WithOne("Weather")
                        .HasForeignKey("CountryWeatherAPI.Models.Weather", "CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CountryWeatherAPI.Models.Country", b =>
                {
                    b.Navigation("Weather")
                        .IsRequired();
                });

            modelBuilder.Entity("CountryWeatherAPI.Models.ResponsiblePerson", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
